### ISSUE TITLE
Swift 1.2

### ISSUE THREAD

**Issue by bolom** [abury/ABPadLockScreen#42]
Hi

with Swift 1.2 the lib doesn't work

bolo

**Comment by abury** [comment]
Hi bolom

Can you provide more detail? What is the issue exactly?

Thanks,

Aron

**Comment by tidane** [comment]
@import UIKit;
 in .h classes of ABPadLockScreen

**Comment by haswalt** [comment]
We have a fork here running with swift 1.2. https://github.com/egeniq-forks/ABPadLockScreen

@abury I can push up some of our code your way if you want? I haven't done yet because of our change to the abstract, currently that breaks things see

**Comment by abury** [comment]
Yep, this has been resolved by PR #48
