### ISSUE TITLE
Support change pin functionality

### ISSUE THREAD

**Issue by lolgear** [abury/ABPadLockScreen#49]
I wonder if there is a change pin lock screen

**Comment by abury** [comment]
Hi @lolgear 
There is already a screen for supporting setting/updating a PIN. Just use ABPadLockScreenSetupViewController and configure it appropriately. The example demo project shows an example of how to use this.

**Comment by lolgear** [comment]
I mean scenario:
input old pin -> set new pin -> set new pin agan.

I can't find it in Setup screen.
