### ISSUE TITLE
How to use ABPadLockScreen with Pods.

### ISSUE THREAD

**Issue by kedardesai** [abury/ABPadLockScreen#67]
I have installed ABPadLockScreen with Pods. I can see all imported files in pods. But I am unable to use those files. I am unable to understand how should i import ABPadLockScreen Module. Can you please provide some description about how to import module and use screens using pods under description of your project.

Right now I am just trying to import using following statement, but it is not importing module.

import ABPadLockScreen

**Comment by abury** [comment]
Hey @kedardesai 😄 

This project hasn't been updated in awhile, so it's possible that it hasn't kept up to date with the latest cocoapods release. You should just be able to import it as you would any other pod. If it's broken then you might need to look at a different project.

Apologies about that. Best of luck with your project!

Aron
